name: Build and Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Get version from gradle.properties
        id: get_version
        run: |
          VERSION=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}-${{ github.run_number }}
          name: Name History v${{ steps.get_version.outputs.version }} (Build ${{ github.run_number }})
          body: |
            ## 💜 Name History Mod
            
            **Version:** ${{ steps.get_version.outputs.version }}
            **Build:** #${{ github.run_number }}
            **Commit:** ${{ github.sha }}
            
            ### Installation
            1. Download the `.jar` file below
            2. Place it in your `.minecraft/mods` folder
            3. Make sure you have [Fabric API](https://modrinth.com/mod/fabric-api) and [Fabric Language Kotlin](https://modrinth.com/mod/fabric-language-kotlin) installed
            
            ### Changelog
            See commit history for changes.
          draft: false
          prerelease: false
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
